### ISSUE TITLE
Multi-formatting a file without workspace

### ISSUE THREAD

**Issue by twardoch** [jota0222/MultiFormatterVSCode#13]
I’ve configured the extension for Markdown files like so: 

```json
    "[markdown]": {
        "editor.defaultFormatter": "Jota0222.multi-formatter",
        "multiFormatter.formatterList": [
            "DavidAnson.vscode-markdownlint",
            "fcrespo82.markdown-table-formatter",
            "esbenp.prettier-vscode"
        ]
    }
```

When I open a Markdown file within a workspace, the multi-formatting works fine. But if I open just a standalone file, then whenever I format, I get a dialog box: 

---

### Command 'MultiFormat Document' resulted in an error

Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.

---

So it seems that MultiFormatter only works with a workspace — which is a big limitation.

**Comment by jota0222** [comment]
@twardoch Thanks for reporting this issue. It has been resolved and pushed into the Extension Store. You should be able to update now and check if it works as expected.
