### ISSUE TITLE
Infinite Saving - eventually crashed

### ISSUE THREAD

**Issue by goper-leo** [jota0222/MultiFormatterVSCode#15]
If I save/format document it will do an infinite loop of switching the formatters, sometimes vscode will crashed due to endless saving of the file.

Steps to reproduce:
- Create `PHP` file
-  Formatters used in order:
    - [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client)
    - [PHP Devsense](https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode)
    
My vscode `settings.json`:
```
"editor.defaultFormatter": "DEVSENSE.phptools-vscode",
        "multiFormatter.formatterList": [
            "bmewburn.vscode-intelephense-client",
            "DEVSENSE.phptools-vscode"
        ]
```

Environment:
```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-39-generic
```

Thanks for making this extension!

**Comment by jota0222** [comment]
Hi @goper-leo, does this happen using just a file without opening a folder or workspace?

**Comment by goper-leo** [comment]
@jota0222 nope, opened on a folder/workspace.

**Comment by jota0222** [comment]
I have deployed a fix. Thank you for reporting it.

Edit: For future refference, the problem was caused by Devsense saving again after formatting, which caused an endless loop when format on save is enabled. I fixed it by adding a state and a validation to check if the composite formatter is already running.
