### ISSUE TITLE
File remains unsaved when formatting on save

### ISSUE THREAD

**Issue by alessandro-newzoo** [jota0222/MultiFormatterVSCode#2]
Hello!
Thank you so much for this beautiful extension, it works like a charm <3

There is one very annoying issue though, which happens when formatting automatically on save.

The multi formatter runs both formatters successfully, but then at the very end of the process it leaves VS Code thinking the file has not been saved.

Notice how `text.php` will show a white circle in its tab as if the file has unsaved changes:

https://user-images.githubusercontent.com/47320294/224004736-69d36028-dd41-46f8-8a6e-061d990f8149.mov

<img width="220" alt="image" src="https://user-images.githubusercontent.com/47320294/224005195-54629481-fa62-4fb8-96f4-bebefa6110e8.png">

---

My settings:

```json
"[php]": {
	"editor.defaultFormatter": "Jota0222.multi-formatter",
	"multiFormatter.formatterList": [
		"wongjn.php-sniffer",
		"bmewburn.vscode-intelephense-client"
	]
}
```

This is annoying because it obviously makes it hard/impossible to keep track of actual unsaved changes.
Do you think there's anything that can be done?

Thanks a lot!

**Comment by alessandro-newzoo** [comment]
@jota0222 sorry to bother but are you able to reproduce this?

**Comment by jota0222** [comment]
Hi @alessandro-newzoo, sorry for the delay. 

Loking for reasons to this, I think the problem can be that the file is saved before the second formatter runs, I will check what I can do.

Thanks for reporting!

**Comment by alessandro-newzoo** [comment]
@jota0222 no worries at all and thanks for your reply! No need to be sorry.
 I wish I had the right skillset to be able to help with a PR but this is out of my area of expertise I'm afraid 😅

**Comment by jota0222** [comment]
Thanks to @asbelljc for fixing this. The change is already published in the Marketplace.
