### ISSUE TITLE
Okay if I submit a few PRs?

### ISSUE THREAD

**Issue by a-laughlin** [jota0222/MultiFormatterVSCode#22]
I want to recommend this plugin for others' use, but encountered some pain points while trying to use it myself.  Is it okay if I make a few PRs to improve error messages?  I can also add support for all languages.

**Comment by jota0222** [comment]
Hi @a-laughlin, go ahead and thank you so much for your help!

I just wanto to let you know I don't have too much time right now, so I'll check the PR's as I have time, which can take a while.

**Comment by a-laughlin** [comment]
Hi Juan.  I hear you on not having much time.

The changes for updating the location of "editor.defaultFormatter" and error logging ended up being significant, so I created a [separate extension](https://github.com/a-laughlin/formatter-sequence/blob/main/src/extension.ts) to use without the PR review delay.  Long term I don't want to maintain a separate extension and would rather contribute to this one.  Once you have time, take a look and let me know if you're interested in incorporating any of the changes.  I'm open to coordinating contributions.

**Comment by jota0222** [comment]
@a-laughlin Yeah, sorry for the big delay. I saw your PR about the configuration levels for the default formatter, that was something really cool. Thanks.

It is already deployed with the latest release.
