### ISSUE TITLE
Slow Performance

### ISSUE THREAD

**Issue by hyperupcall** [jota0222/MultiFormatterVSCode#5]
This is a very useful extension! I'm glad this exists - however I would like to mention that there is a bit of a performance issue.

After configuring MultiFormatter with two formatters, it takes about 3 seconds to "save". Meanwhile, each individual formater takes almost instantly when each are ran individually. Is there something specific that might be slowing things down?

**Comment by jota0222** [comment]
Hi @hyperupcall , sorry for delayed reply.

Would you mind to add the formatter you use so I can check?

Thanks!

**Comment by hyperupcall** [comment]
Yup, I used [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).
